# SEND OTP 
POST http://localhost:5000/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone":"8967888480"
}

###
POST http://localhost:5000/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "phone":"8967888480",
    "otp":"5174",
    "hash":"b66a1346f0ed1f7ed779d184e1a0af1cbc9c06d5680e7d54cbb51dcdb0cd4b0d.1647353044209"
}
